### ISSUE TITLE
[Fixed] Decoding large strings

### ISSUE THREAD

**Issue by firepacket** [kzrnm/Base32768#8]
Easy fix for decoding large files. 
Base32768.cs line 273

Change:
`var length = str.Length * BITS_PER_CHAR / BITS_PER_BYTE;`
to:
`long length = (long)str.Length * BITS_PER_CHAR / BITS_PER_BYTE;`

**Comment by kzrnm** [comment]
OK, `(long)str.Length * BITS_PER_CHAR` is better!
But I think `length` should be int because array cannot have too long length.

Please, make a new pull request!

**Comment by firepacket** [comment]
Well the reason I'm even interested in this library is I'm dealing with very long strings! Maybe foolish, but it's working for me.
To be honest, I don't know how to make a pull request...

**Comment by kzrnm** [comment]
@firepacket 

##  how to make a pull request

1.  Fork this repository.
2. Make new branch and commit some changes.
3. Make a new pull request from forked.

https://docs.github.com/en/free-pro-team@latest/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request-from-a-fork

**Comment by firepacket** [comment]
Well maybe we should fix that? The maximum data a BigStringBuilder can hold is about 32GB bypassing the .NET object limit. Could definitely be useful for servers.

And I'd like to encode bigger files too. How about it? Few drawbacks. it is a little slower than a StringBuilder when appending but I honestly don't notice it I would say the delay was caused by the filesystem when I tested it. But I was able to load a 20GB file into this object and everything worked as expected and it wasn't that slow or anything. (i have 32gb ram).

Imagine encoding a 4gb movie into a TEXT FILE with possibly smaller size if you add compression!

```
public class BigStringBuilder
{
	List<char[]> c = new List<char[]>();
	private int pagedepth;
	private long pagesize;
	// https://stackoverflow.com/questions/11040646/faster-modulus-in-c-c
	private long mpagesize; 
	private int currentPage = 0;
	private int currentPosInPage = 0;

	public BigStringBuilder(int pagedepth = 12)  // pagesize is 2^pagedepth (since must be a power of 2 for a fast indexer)
	{   
		this.pagedepth = pagedepth;
		pagesize = (long)Math.Pow(2, pagedepth);
		mpagesize = pagesize - 1;
		c.Add(new char[pagesize]);
	}

	
	public char this[long n] // Indexer for this class, so you can use convenient square bracket indexing to address char elements within the array!!
	{
		get { return c[(int)(n >> pagedepth)][n & mpagesize]; }
		set { c[(int)(n >> pagedepth)][n & mpagesize] = value; }
	}


	public void Clear()
	{
		c = new List<char[]>{new char[pagesize]};
		currentPage = 0;
		currentPosInPage = 0;
	}

	public long Length()
	{
		return (long)currentPage * (long)pagesize + (long)currentPosInPage;
	}

	public string ToString(long max = 2000000000)
	{
		if (Length() < max) return Substring(0, Length());
		else return Substring(0, max);
	}

	public string Substring(long x, long y)
	{
		StringBuilder sb = new StringBuilder();
		for (long n = x; n < y; n++)
			sb.Append(c[(int)(n >> pagedepth)][n & mpagesize]);    //8s
		return sb.ToString();
	}

	public bool Match(string find, long start = 0)
	{
		for (int i = 0; i < find.Length; i++) if (i + start == find.Length || this[start + i] != find[i]) return false;
		return true;
	}

	public void Replace(string s, long pos)
	{
		for (int i = 0; i < s.Length; i++)
		{
			c[(int)(pos >> pagedepth)][pos & mpagesize] = s[i];
			pos++;
		}
	}

	public void Append(char ch)
	{
		c[currentPage][currentPosInPage] = ch;
		updatePages();
	}

	public void Append(string s)
	{
		for (int i = 0; i < s.Length; i++)
		{
			c[currentPage][currentPosInPage] = s[i];
			updatePages();
		}
	}

	void updatePages()
	{
		currentPosInPage++;
		if (currentPosInPage == pagesize)
		{
			currentPosInPage = 0;
			currentPage++;
			if (currentPage == c.Count) c.Add(new char[pagesize]);
		}
	}


	public void LoadFile(string path)
	{
		Clear();
		StreamReader sw = new StreamReader(path);
		int len = 0;
		while ((len = sw.ReadBlock(c[currentPage], 0, (int)pagesize)) != 0)
		{
			if (!sw.EndOfStream)
			{
				currentPage++;
				if (currentPage > (c.Count - 1)) c.Add(new char[pagesize]);
			}
			else
			{
				currentPosInPage = len;
				break;
			}
		}
		sw.Close();
	}

	public void SaveFile(string path)
	{
		StreamWriter sw = File.CreateText(path);
		for (int i = 0; i < currentPage; i++) sw.Write(new string(c[i]));
		sw.Write(new string(c[currentPage], 0, currentPosInPage));
		sw.Close();
	}
}
```

I'm not quite sure how this magic works to be able to do this with just a single List<> and some math. For it to be useful in my projects some other objects are going to have to get a similar treatment. But I definitely think it would help in your project. 

I mean isn't that what your project is all about?  Making big text files more compact? This tool is squarely aimed at you! I'm too lazy to do all the forking and stuff right now but I might if I keep going on this project. Anyway, I hope you like it.!

**Comment by firepacket** [comment]
It's crazy won't his .ToString() crash anything over max? There needs to be a stream function.

**Comment by kzrnm** [comment]
I add stream API in #9.

@firepacket What do you think?

**Comment by firepacket** [comment]
It looks great man! With all the nice structs they have in .NET Standard you aren't going to have to worry about length. Unfortunately I'm still on .Net Framework 4.6 and I"m scared to switch due to some other funky libraries I'm using in my code base.

But you did a good job solving it by moving to .Net Standard which I saw you had already started doing. Seeing as how .Net Standard seems to encompass everything, I will do my best to see if I can port my project over too. It looks like that might be the future and I might be able to get multi-platform support out of it! Thanks for the encouragement!

**Comment by kzrnm** [comment]
@firepacket .NET Framework 4.6 implements .NET Standard 1.3. You can use this library in your .NET Framework 4.6 project.
